export default {
	ADD: 'ADD_TASK',
	TOGGLE_COMPLITED: 'TOOGLE_COMPLITED',
	REMOVE: 'REMOVE_TASK',
	TOGGLE_IMPORTANT: 'TOOGLE_IMPORTANT',

	FILTER_COMPLITED: 'FILTER_COMPLITED',
	FILTER_ACTIVE: 'FILTER_ACTIVE',
}
